on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  frontend:
    name: Deploy To AWS
    runs-on: ubuntu-22.04
    
    steps:
     
      - name: Checking Code Out
      - uses: actions/checkout@v4
     
      - name: Sync To S3
        run: |
          aws s3 sync app/ $BUCKET_NAME --delete
    
      - name : Cache Invalidation on CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths '/*'
      
